services:
  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"
      - "7001:7001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.pdc/floci-data:/data
    environment:
      - FLOCI_HOSTNAME=floci
      - FLOCI_DEFAULT_REGION=us-east-1
      - FLOCI_STORAGE_MODE=hybrid
      - FLOCI_STORAGE_PERSISTENT_PATH=/data
